### PR TITLE
fix import paths

### LINKED ISSUE #236: OpenZeppelin import issues
I think the issue has to do with submodules and how Forge handles these. I suspect this just isnt playing nicely with the open zeppelin contracts, which are installed with Forge and through NPM.

### PR DESCRIPTION
**Pull request by 0xZakk**
Fixes #236

I've added the `eas-contracts` with Foundry. I've also changed the EAS and OpenZeppelin import paths to pull from `lib/` instead of from `node_modules/`. This is what was causing errors when someone installed the `allo-v2` repo using Foundry.

Commits:
- add and configure hardhat preprocessor
- forge install: eas-contracts
- update import paths to pull from foundry's lib/ and not from node_modules

Flagging that it looks like the build scripts are broken or not documented correctly? What's in the `DEPLOY_STEPS.md` doc is different from what's in the npm scripts in `package.json` is also different from what's in the `scripts/` directory. Can we add that to #223?

### CODE REVIEW

**Comment by 0xKurt** [comment]
@thelostone-mc @0xZakk does the test fail for you too? I can't reproduce the failing test locally and therefore i can't look into fixing it.

**Comment by 0xZakk** [comment]
@0xKurt should be good now

**Comment by 0xZakk** [comment]
@0xKurt all set

**Review by 0xKurt — APPROVED** [review]
lgtm!

**Review by 0xKurt — APPROVED** [review]

**Review by 0xKurt — APPROVED** [review]

**Pull request merged**
