### PR TITLE
add registration start/end time to direct grants strategy

### PR DESCRIPTION
**Pull request by gravityblast**
closes https://github.com/gitcoinco/grants-stack/issues/2961

### CODE REVIEW

**Review by codenamejason — APPROVED** [review]
Strange to me we are allowing start dates in the past (I'm sure there is a reason). And... I just saw the other PR 😂

**Review by thelostone-mc — APPROVED** [review]

**Review by 0xKurt — CHANGES_REQUESTED** [review]
Timestamps are unused.

Fix: introduce an `onlyActiveRegistration` modifier which checks the block timestamp and add it to `_registerRecipient`

@gravityblast

**Comment by gravityblast** [comment]
@0xKurt great catch thank you! I pushed a fix

**Comment by gravityblast** [comment]
> Strange to me we are allowing start dates in the past (I'm sure there is a reason). And... I just saw the other PR 😂

the reason is that we need to allow any change in the dates. But if we don't allow to set the start time in the past, we would need to update it to `now` every time we want to extend the end date

**Review by 0xKurt — APPROVED** [review]

**Pull request merged**
