### PR TITLE
feat/sablier strategies  (#139)

### PR DESCRIPTION
**Pull request by codenamejason**
Adds Sablier Strategies.
- Lockup Linear
- Lockup Dynamic

Would like to see 100% on test coverage when `yarn coverage:report` and `yarn coverage:html` are run.

### CODE REVIEW

**Comment by KurtMerbeth** [comment]
@PaulRBerg @andreivladbrg 
Because of the mainnet fork the tests are very slow and hold up the github action. 
Would it be possible to use a mock contracts instead?

**Comment by andreivladbrg** [comment]
Hey @KurtMerbeth , we could do that, but I want to mention that there is one more way to fix this, and that is to add the `--no-match-test "testFork"` flag in the `.yml` file:

https://github.com/allo-protocol/allo-v2/blob/b5ff15829608795fc6622b6c828312c48136fba1/.github/workflows/forge-test.yml#L44-L46

The full command: `forge test --no-match-test "testFork"`

From my perspective, when connecting two systems (allo-v2 + sablier-v2), fork tests are the best choice to go for.

Please tell me the option you prefer to go for, and I will make the changes.

**Comment by codenamejason** [comment]
> Hey @KurtMerbeth , we could do that, but I want to mention that there is one more way to fix this, and that is to add the `--no-match-test "testFork"` flag in the `.yml` file:
> 
> https://github.com/allo-protocol/allo-v2/blob/b5ff15829608795fc6622b6c828312c48136fba1/.github/workflows/forge-test.yml#L44-L46
> 
> The full command: `forge test --no-match-test "testFork"`
> 
> From my perspective, when connecting two systems (allo-v2 + sablier-v2), fork tests are the best choice to go for.
> 
> Please tell me the option you prefer to go for, and I will make the changes.

This makes sense to me and happy to make the change (I don't want to create a new PR for a small change if we don't need to). cc: @KurtMerbeth

**Comment by PaulRBerg** [comment]
I agree with @andreivladbrg that it's best to rely on fork tests when integrating two extensive protocols like Sablier and Allo, and that excluding (our) fork tests from the daily CI runs seems like the way to go to mitigate the issue with the long CI run times.

As a side note: what you could consider doing is creating another CI that runs occasionally, say, only once per week. For example, this is how we configured our "CI Deep" workflow:

https://github.com/sablier-labs/v2-core/blob/fcbc567aea6362c1f102eb19732badeb4899dec5/.github/workflows/ci-deep.yml

**Comment by PaulRBerg** [comment]
I've also just seen your review [here](https://github.com/allo-protocol/allo-v2/pull/139#discussion_r1282560069), @codenamejason. Sorry, I was on holiday for a few days.

It looks like you made the refactor from `Identity` to `Profile` yourself? Thank you!

However, your latest commit message says "need assist" - what else needs fixing? we would be happy to help.

**Comment by codenamejason** [comment]
@PaulRBerg I was working on the tests to add additional coverage and update some items and ran into this:

Screenshot 2023-08-08 at 9 14 25 AM

**Comment by PaulRBerg** [comment]
@andreivladbrg, PTAL.

**Comment by codenamejason** [comment]
@andreivladbrg you can try to push but think you may need a PR to this branch (permissions) and I can merge it in.

**Comment by andreivladbrg** [comment]
Yes, I couldn't push directly. I created a PR: https://github.com/allo-protocol/allo-v2/pull/170

**Comment by codenamejason** [comment]
@KurtMerbeth @thelostone-mc not sure what is happening here with the build. It is not failing locally for me.

**Comment by codenamejason** [comment]
I wanted to call out that `npx hardhat` aren't working currently on this branch due to the Sablier remapping. We are using HH for our deploy scripts and other web3 scripts. Foundry did not support upgradeable proxy creation.

cc: @thelostone-mc @KurtMerbeth

**Comment by KurtMerbeth** [comment]
@andreivladbrg @PaulRBerg 

We rely on hardhat for our deployments, currently it is not possible to use your node module with hardhat since the imported library `@prb/math/*.sol` is not a valid node module path. The path is missing `/src` => `@prb/math/src/*.sol` 

We could now build some work around to make it work, but that's not the right approach. Maybe it would also be in your interest, and in the interest of your users, or other developers, to  adjust the import path. WDYT?

cc: @thelostone-mc @codenamejason

**Comment by andreivladbrg** [comment]
Hi @KurtMerbeth @codenamejason, thanks for reporting it. We are aware of this issue and unfortunately we did not have time to address it https://github.com/sablier-labs/v2-core/issues/646.

In the mean time, the short solution would be to add `import "@nomicfoundation/hardhat-foundry";` in the `hardhat.config.ts` file:

**Comment by thelostone-mc** [comment]
@codenamejason Let's add `import "@nomicfoundation/hardhat-foundry";` into our config

**Comment by codenamejason** [comment]
Still getting same error after adding `import "@nomicfoundation/hardhat-foundry";` in the `hardhat.config.ts`

Screenshot 2023-08-11 at 1 19 09 PM

Screenshot 2023-08-11 at 1 19 58 PM

**Comment by PaulRBerg** [comment]
Hey guys, I am very sorry for this. Trying to make a Foundry project work in a Hardhat project is mission impossible .. bugs piled on top of other bugs piled on top of other bugs:

https://github.com/NomicFoundation/hardhat/issues/4194

> Still getting same error after adding import "@nomicfoundation/hardhat-foundry"; in the hardhat.config.ts

You also need to add the following remappings:

```txt
@prb/math/=node_modules/@prb/math/src/
@sablier/v2-core/=node_modules/@sablier/v2-core/src/
```

Although not even this would be enough for the reason given [here](https://github.com/NomicFoundation/hardhat/issues/4194#issuecomment-1674546379).

> Maybe it would also be in your interest, and in the interest of your users, or other developers, to adjust the import path. WDYT?

100% agree. We will update the import paths to use `src/`. However, I cannot give a specific ETA for this because we would need to make some thorough tests before publishing the new packages to npm.

Would copy-pasting the required interfaces be a solution in the short term? 😬

**Comment by codenamejason** [comment]
> Would copy-pasting the required interfaces be a solution in the short term? 😬

I am okay with this as a temporary solution. I think it's only the `UD2x18.sol`.

**Comment by codenamejason** [comment]
> Trying to make a Foundry project work in a Hardhat project is mission impossible .. bugs...

We would have stayed strictly with Foundry but it didn't support all of our current needs and had to add Hardhat for deployments.

**Comment by PaulRBerg** [comment]
> I am okay with this as a temporary solution. I think it's only the UD2x18.sol.

Great. @andreivladbrg, could you pick up this task tomorrow, thank you.

**Comment by andreivladbrg** [comment]
Hey, just want to give an updated regarding the issue with Hardhat. I've created a PR in our v2-core repo: https://github.com/sablier-labs/v2-core/pull/648. This PR changes the import path, and it should resolve the issue. I manually changed the imports in the node_modules directory in the sablier-strategies branch, and it compiled:

image

If this solution doesn't work, I've also created a branch that removes the lib(v2-core) from the repo and adds the external interfaces and types. : https://github.com/sablier-labs/allo-v2/commit/e1f17b6e93120ffa66d91f34e7f07988bbc448bd.

I haven't created a PR for this branch yet, as we will likely release a new version of the packages tomorrow.

**Comment by codenamejason** [comment]
thank you very much @andreivladbrg

**Comment by PaulRBerg** [comment]
Hey guys, we are glad to let you know that we just shipped v1.0.2 of the [`@sablier/v2-core`](https://www.npmjs.com/package/@sablier/v2-core) package on npm, which should address all of the import paths bug you bumped into.

Compiling with both Forge and Hardhat should work now!

You can cherry-pick my commit here:

https://github.com/sablier-labs/allo-v2/tree/feat/sablier-strategies

**Comment by codenamejason** [comment]
@andreivladbrg is there anything we can do to help get this across the finish line so we can merge this in?

I think all that is left is some test coverage.

cc: @thelostone-mc @KurtMerbeth

**Comment by andreivladbrg** [comment]
> I think all that is left is some test coverage.

Yes, that's it. Sorry for delaying it, we are a small team.

I will try tomorrow to finish all the tests.

**Comment by andreivladbrg** [comment]
Hello @codenamejason 

I managed to finish the tests and I created a PR https://github.com/allo-protocol/allo-v2/pull/244.

Looks like there is 100% on test coverage now:
Screenshot 2023-08-24 at 11 33 30 AM
Screenshot 2023-08-24 at 11 32 54 AM

Lmk if there is anything left.

**Comment by andreivladbrg** [comment]
Hey guys, I just wanted to check in and see if everything's ok. Is the PR ready to be merged? @codenamejason @0xKurt @thelostone-mc

**Comment by codenamejason** [comment]
> Hey guys, I just wanted to check in and see if everything's ok. Is the PR ready to be merged? @codenamejason @0xKurt @thelostone-mc

Everything looks good running locally, just the GH actions are acting differently for some reason.

Screenshot 2023-08-28 at 10 04 00 AM

**Comment by 0xKurt** [comment]
> Hey guys, I just wanted to check in and see if everything's ok. Is the PR ready to be merged? @codenamejason @0xKurt @thelostone-mc

Looks good! Will approve it now. Thanks for building these strategies!

**Review by 0xKurt — APPROVED** [review]

**Pull request merged**
